version: '3.8'

services:
  evaluation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evaluation-service
    ports:
      - "8084:8084"
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-your_secure_jwt_secret}
      LOG_DIR: /app/logs
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5173}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - mtn-network
    restart: unless-stopped

networks:
  mtn-network:
    driver: bridge
