version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - mtn-network
#    depends_on:
#      - user-service
#      - application-service
#      - evaluation-service
#      - notification-service
#      - dashboard-service
#      - guardian-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/gateway/status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - TZ=America/Santiago

  user-service:
    image: user-service:latest
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - mtn-network
    depends_on:
      - postgres

  application-service:
    image: application-service:latest
    container_name: application-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    networks:
      - mtn-network
    depends_on:
      - postgres

  evaluation-service:
    image: evaluation-service:latest
    container_name: evaluation-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    networks:
      - mtn-network
    depends_on:
      - postgres

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    networks:
      - mtn-network
    depends_on:
      - postgres

  dashboard-service:
    image: dashboard-service:latest
    container_name: dashboard-service
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks:
      - mtn-network
    depends_on:
      - postgres

  guardian-service:
    image: guardian-service:latest
    container_name: guardian-service
    restart: unless-stopped
    ports:
      - "8087:8087"
    networks:
      - mtn-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: mtn-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
      POSTGRES_DB: ${DB_NAME:-Admisión_MTN_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mtn-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mtn-network:
    driver: bridge

volumes:
  postgres-data:
